LAIVE.V1/Areas/DI/Controllers/AsignacionPedidoController.cs
using Laive.Core.Common;
using Laive.Core.Data;
using Laive.Core.Entity;
using LAIVE.V1.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DIBOQry = Laive.BOQry.Di;
using BIBOQry = Laive.BOQry.Bi;
using Laive.Entity.Di;
using Laive.Entity.Bi;
using System.Web.Script.Serialization;
using DIBOMnt = Laive.BOMnt.Di;
using Newtonsoft.Json;

namespace LAIVE.V1.Areas.DI.Controllers
{
   public class AsignacionPedidoController : SamcontrollerBase
   {
      [HttpGet]
      public PartialViewResult Index()
      {
         return PartialView("Index");
      }

      [HttpGet]
      public PartialViewResult GetAsignacionPedido(string fechaAsignacion, int tipoAsignacion)
      {
         IBOQuery objBOAlmacen = (IBOQuery)WCFHelper.GetObject<IBOQuery>(typeof(DIBOQry.Almacen));
         EAlmacen eAlmacen = new EAlmacen();
         ICollection<EAlmacen> listAlma = objBOAlmacen.GetList<EAlmacen>(eAlmacen);
         ViewBag.ListAlmacen = listAlma;
         ViewBag.TipoAsignacion = tipoAsignacion;
         var jsonSerialiser = new JavaScriptSerializer();
         ViewBag.ListAlmacenString = jsonSerialiser.Serialize(listAlma);
         Session["FechaAsignacion"] = fechaAsignacion;
         Session["TipoAsignacion"] = tipoAsignacion;
         ViewBag.fechaDespacho = fechaAsignacion;
         
         IBOQuery objBOCanalComercial = (IBOQuery)WCFHelper.GetObject<IBOQuery>(typeof(BIBOQry.CanalComercial));
         ECanalComercial eCanalComercial = new ECanalComercial();
         ICollection<ECanalComercial> canalComercialLista = objBOCanalComercial.GetList<ECanalComercial>(eCanalComercial);
         string JsonCanalComercial = "";
         foreach (ECanalComercial eSel in canalComercialLista)
         {
            if (JsonCanalComercial != "")
               JsonCanalComercial = string.Concat(JsonCanalComercial, ",");
            JsonCanalComercial = string.Concat(JsonCanalComercial, "{text: '", string.Concat(eSel.Codigo, " - ", eSel.Glosa), "', value: '", eSel.Codigo, "'}");
         }
         ViewBag.ListaCanalComercial = JsonCanalComercial;
         

         IBOQuery BOtipoResultadoAsignacion = (IBOQuery)WCFHelper.GetObject<IBOQuery>(typeof(DIBOQry.TipoResultadoAsignacion));
         ETipoResultadoAsignacion eTipoResultadoAsignacion = new ETipoResultadoAsignacion();
         ICollection<ETipoResultadoAsignacion> listTipoResultadoAsignacion = BOtipoResultadoAsignacion.GetList<ETipoResultadoAsignacion>(eTipoResultadoAsignacion);
         string JsonTipoResultadoAsignacion = "";
         foreach (ETipoResultadoAsignacion eSel in listTipoResultadoAsignacion)
         {
            if (JsonTipoResultadoAsignacion != "")
               JsonTipoResultadoAsignacion = string.Concat(JsonTipoResultadoAsignacion, ",");
            JsonTipoResultadoAsignacion = string.Concat(JsonTipoResultadoAsignacion, "{text: '", string.Concat(eSel.CodigoResultado, " - ", eSel.GlosaResultado), "', value: '", eSel.CodigoResultado, "'}");
         }
         ViewBag.TipoResultados = JsonTipoResultadoAsignacion;


         IBOQuery objBOCanalBaan = (IBOQuery)WCFHelper.GetObject<IBOQuery>(typeof(DIBOQry.BaanCanal));
         EBaanCanal eBaanCanal = new EBaanCanal();
         ICollection<EBaanCanal> listCanalBaan = objBOCanalBaan.GetList<EBaanCanal>(eBaanCanal);
         string JsonCanalBaan = "";
         foreach (EBaanCanal eSel in listCanalBaan)
         {
            if (JsonCanalBaan != "")
               JsonCanalBaan = string.Concat(JsonCanalBaan, ",");
            JsonCanalBaan = string.Concat(JsonCanalBaan, "{text: '", eSel.GlosaCanal, "', value: '", eSel.CodigoCanal, "'}");
         }
         ViewBag.CanalBaan = JsonCanalBaan;

         IBOQuery objBOPartner = (IBOQuery)WCFHelper.GetObject<IBOQuery>(typeof(DIBOQry.BaanPartner));
         EBaanPartner eBaanPartner = new EBaanPartner();
         ICollection<EBaanPartner> partnerLista = objBOPartner.GetList<EBaanPartner>(eBaanPartner);
         var JsonPartner = from partner in partnerLista select new { text = String.Concat(partner.CodigoPartner.Trim(), " - ", partner.ClavePartner1.Trim()), value = partner.CodigoPartner.Trim() };
         ViewBag.ListaPartner = JsonConvert.SerializeObject(JsonPartner);


         IBOQuery objBO = (IBOQuery)WCFHelper.GetObject<IBOQuery>(typeof(DIBOQry.BaanCategoria));
         EBaanCategoria eBaanCategoria = new EBaanCategoria();
         ICollection<EBaanCategoria> listCategoria = objBO.GetList<EBaanCategoria>(eBaanCategoria);
         string JsonCategoria = "";
         foreach (EBaanCategoria eSel in listCategoria)
         {
            if (JsonCategoria != "")
               JsonCategoria = string.Concat(JsonCategoria, ",");
            JsonCategoria = string.Concat(JsonCategoria, "{text: '", string.Concat(eSel.CodigoCategoria, " - ", eSel.GlosaCategoria), "', value: '", eSel.CodigoCategoria, "'}");
         }
         ViewBag.Categorias = JsonCategoria;


         IBOQuery objBOMarca = (IBOQuery)WCFHelper.GetObject<IBOQuery>(typeof(DIBOQry.BaanMarca));
         EBaanMarca eBaanMarca = new EBaanMarca();
         ICollection<EBaanMarca> listMarca = objBOMarca.GetList<EBaanMarca>(eBaanMarca);
         string JsonMarca = "";
         foreach (EBaanMarca eSel in listMarca)
         {
            if (JsonMarca != "")
               JsonMarca = string.Concat(JsonMarca, ",");
            JsonMarca = string.Concat(JsonMarca, "{text: '", string.Concat(eSel.CodigoMarca, " - ", eSel.GlosaMarca), "', value: '", eSel.CodigoMarca, "'}");
         }
         ViewBag.Marcas = JsonMarca;


         IBOQuery objBOSubMarca = (IBOQuery)WCFHelper.GetObject<IBOQuery>(typeof(DIBOQry.BaanSubMarca));
         EBaanSubMarca eBaanSubMarca = new EBaanSubMarca();
         ICollection<EBaanSubMarca> listSubMarca = objBOSubMarca.GetList<EBaanSubMarca>(eBaanSubMarca);
         string JsonSubMarca = "";
         foreach (EBaanSubMarca eSel in listSubMarca)
         {
            if (JsonSubMarca != "")
               JsonSubMarca = string.Concat(JsonSubMarca, ",");
            JsonSubMarca = string.Concat(JsonSubMarca, "{text: '", string.Concat(eSel.CodigoSubMarca, " - ", eSel.GlosaSubMarca), "', value: '", eSel.CodigoSubMarca, "'}");
         }
         ViewBag.SubMarcas = JsonSubMarca;


         IBOQuery objBOPresentacion = (IBOQuery)WCFHelper.GetObject<IBOQuery>(typeof(DIBOQry.BaanPresentacion));
         EBaanPresentacion eBaanPresentacion = new EBaanPresentacion();
         ICollection<EBaanPresentacion> listPresentacion = objBOPresentacion.GetList<EBaanPresentacion>(eBaanPresentacion);
         string JsonPresentacion = "";
         foreach (EBaanPresentacion eSel in listPresentacion)
         {
            if (JsonPresentacion != "")
               JsonPresentacion = string.Concat(JsonPresentacion, ",");
            JsonPresentacion = string.Concat(JsonPresentacion, "{text: '", string.Concat(eSel.CodigoPresentacion, " - ", eSel.GlosaPresentacion), "', value: '", eSel.CodigoPresentacion, "'}");
         }
         ViewBag.Presentaciones = JsonPresentacion;

         IBOQuery objBOBaanArticulo = (IBOQuery)WCFHelper.GetObject<IBOQuery>(typeof(DIBOQry.BaanArticulo));
         EBaanArticulo eBaanArticulo = new EBaanArticulo();
         ICollection<EBaanArticulo> articuloLista = objBOBaanArticulo.GetList<EBaanArticulo>(eBaanArticulo);
         string JsonArticulo = "";
         foreach (EBaanArticulo eSel in articuloLista)
         {
             if (JsonArticulo != "")
                 JsonArticulo = string.Concat(JsonArticulo, ",");
             JsonArticulo = string.Concat(JsonArticulo, "{text: '", string.Concat(eSel.CodigoArticulo, " - ", eSel.GlosaArticulo), "', value: '", eSel.CodigoArticulo, "'}");
         }
         ViewBag.ListaArticulo = JsonArticulo;

         return PartialView();
      }

      [HttpPost]
      public JsonResult GetDataArticulos(FlexigridParamSamNet Param)
      {
         DIBOQry.IOrdenVenta objBO = (DIBOQry.IOrdenVenta)WCFHelper.GetObject<DIBOQry.IOrdenVenta>(typeof(DIBOQry.OrdenVenta));
         EOrdenVentaArticulo objE = new EOrdenVentaArticulo();
         objE.FechaPrograma = DateTime.Parse(Session["FechaAsignacion"].ToString());
         objE.TipoAsignacion = Int32.Parse(Session["TipoAsignacion"].ToString());

         if (Param.query != null && Param.query != "[]" && Param.query != "")
         {
            JavaScriptSerializer ser = new JavaScriptSerializer();
            List<FilterOperator> filtros = ser.Deserialize<List<FilterOperator>>(Param.query).OrderBy(x => x.fcampo).ToList();

            int countGroupWhere = 0;
            string pivotCampo = "";
            string where = "AND ";
            string whereGroup = "";


            foreach (FilterOperator item in filtros)
            {
               if (pivotCampo != item.fcampo)
               {
                  if (countGroupWhere != 0)
                  {
                     where = string.Concat(where, "( ", whereGroup, " ) AND");
                     whereGroup = "";
                  }

                  whereGroup = string.Concat(item.fcampo, " ", item.fconector, " '", item.fvalue,"' ");
                  countGroupWhere = 1;
                  pivotCampo = item.fcampo;
               }
               else
               {
                  whereGroup = string.Concat(whereGroup, " OR ", item.fcampo, " ", item.fconector, " '", item.fvalue,"' ");
                  countGroupWhere++;
               }

            }

            if (countGroupWhere != 0)
            {
               where = string.Concat(where, "( ", whereGroup, " )");
            }
         
            objE.EntityFilter = where;

         }
         
         var ActProy = objBO.GetOrdenVentaArticulos<EOrdenVentaArticulo>(objE);

         JsonSamNet jsonR = new JsonSamNet();
         jsonR.rows = jsonR.resultArray<EOrdenVentaArticulo>(objE.ColumnSet(), ActProy);

         return Json(jsonR);
      }

      [HttpPost]

LAIVE.V1/Areas/DI/Views/AsignacionPedido/Index.cshtml
<div id="fechaDespacho">
   <div class="bodybuscador">
      <div class="HBox" style=" width:100%;">
         <div class="samnetEditor" style=" height: 30px;">
            <select id="ddlTipoAsignacion" style="width:214px;" class="text-box">
               <option value="1">Pedidos AL</option>
               <option value="2" selected="selected">Pedidos DEL</option>
            </select>
         </div>
      </div>
      <div class="HBox" style=" width:100%;">
         <div class="samnetEditor" style=" height: 30px;">
            <input id="txtFecha" type="text" class="text-box" style="width: 208px;" value="@DateTime.Now.ToString("dd/MM/yyyy")" />
         </div>
      </div>
      <div class="HBox" style=" width:100%; height:10px;">
      </div>
      <div class="HBox" style=" width:100%;">
         <div class="samnetButton" style=" text-align:right;">
            <input id="btnAceptar" type="button" value="Aceptar" class="btnClassButton" style="width:100px;" />
         </div>
      </div>
   </div>
</div>
<script type="text/javascript">
       $(document).ready(function () {
            $('#txtFecha').Zebra_DatePicker({format:'d/m/Y'});

             $("#btnAceptar").click(function() {
                var validate = true;
                    validate = validate && SamControlEsValido("txtFecha", "Se Requiere este dato.");
                    if (!validate)
                        return false;

                    samlinkajaxData('@Url.Action("GetAsignacionPedido", "AsignacionPedido", new { area = "DI" })', { fechaAsignacion: document.getElementById("txtFecha").value, tipoAsignacion: document.getElementById("ddlTipoAsignacion").value }, 'idContentPageAjax', true, true);
                    $("#fechaDespacho").dialog("close");
                    $("#fechaDespacho").dialog('destroy').remove();
            });

             $("#fechaDespacho").dialog({
                    appendTo: "#idContentPageAjax",
                    autoOpen: true,
                    modal: true,
                    draggable: false,
                    resizable: false,
                    width: 250,
                    height : 140,
                    title: "Ingrese la Fecha a Trabajar",
                    show: {
                        effect: "drop",
                        duration: 250
                    },
                    hide: {
                        effect: "drop",
                        duration: 250,
                        direction: "right"
                    }
            });

       });


</script>